# Generated by Django 3.2.6 on 2021-08-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210803_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
